src/Ninja/Lunch/LunchBundle/Entity/FoodOrder.php
<?php

namespace Ninja\Lunch\LunchBundle\Entity;

use Ninja\Lunch\LunchBundle\Entity\FoodOrder\Item;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Ninja\Lunch\LunchBundle\Entity\FoodOrder
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass = "Ninja\Lunch\LunchBundle\Entity\FoodOrderRepository" )
 */
class FoodOrder
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime $date
     *
     * @ORM\Column(name="date", type="date", unique=true)
     */
    private $date;

    /**
     * @var boolean $locked If an order is no longer accepting items
     *
     * @ORM\Column(name="is_locked", type="boolean")
     */
    private $locked = false;

    /**
     * @ORM\OneToMany(targetEntity="Ninja\Lunch\LunchBundle\Entity\FoodOrder\Item", mappedBy="order")
     */
    private $items;

    /**
     * Set the date to be today
     */
    public function __construct(){
        $this->date = new \DateTime();
        $this->items = new ArrayCollection();
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return FoodOrder
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set locked
     *
     * @param boolean $locked
     * @return FoodOrder
     */
    public function setLocked($locked = true)
    {
        $this->locked = $locked;

        return $this;
    }

    /**
     * Get locked
     *
     * @return boolean If the order is locked
     */
    public function getLocked()
    {
        return $this->locked;
    }

    /**
     * Set items
     *
     * @param array $items
     * @return FoodOrder
     */
    public function setItems($items)
    {
        $this->items = $items;

        return $this;
    }

    /**
     * Get items
     *
     * @return ArrayCollection
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Get price
     *
     * @return float The price of this order
     */
    public function getPrice()
    {
        $price = 0;
        foreach($this->getItems() as $item) {
            $price += $item->getPrice();
        }

        return $price;
    }

    /**
     * Get amount paid
     *
     * @return float The amount paid for this order
     */
    public function getAmountPaid()
    {
        $price = 0;
        foreach($this->getItems() as $item) {
            $price += $item->getAmountPaid();
        }

        return $price;
    }

    /**
     * Get amount owing
     *
     * @return float The amount of money owing on this order
     */
    public function getAmountOwing()
    {
        return $this->getPrice() - $this->getAmountPaid();
    }

    /**
     * Get items
     *
     * @return ArrayCollection
     */
    public function getParticipants()
    {
        $found = array();

        return $this->items->filter(function($order) use (&$found) {
            if(in_array($order->getUser()->getId(), $found)) {
                return false;
            }

            $found[] = $order->getUser()->getId();

            return true;
        })->map(function($order) {
            return $order->getUser();
        });
    }

    public function createItem(){
        $item = new Item();
        $item->setOrder($this);

        return $item;
    }

    public function __toString(){
        return sprintf('Order for %s', $this->getDate()->format('Y-m-d'));
    }
}

src/Ninja/Lunch/LunchBundle/Controller/FoodOrder/ItemController.php
<?php

namespace Ninja\Lunch\LunchBundle\Controller\FoodOrder;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Ninja\Lunch\LunchBundle\Entity\FoodOrder;
use Ninja\Lunch\LunchBundle\Entity\FoodOrder\Item;
use Ninja\Lunch\LunchBundle\Form\FoodOrder\ItemType;

use JMS\DiExtraBundle\Annotation as DI;
use JMS\SecurityExtraBundle\Annotation as Security;

/**
 * FoodOrder\Item controller.
 *
 * @Route("/orders/{order}/items")
 */
class ItemController extends Controller
{
    /**
     * @DI\Inject
     */
    private $session;

    /**
     * @param Request The request
     */
    private $request;

    /**
     * @DI\Inject("doctrine.orm.entity_manager")
     */
    private $em;

    /**
     * @DI\Inject("ninja_lunch.order_item_repo")
     */
    private $repo;

    /**
     * @DI\Inject("ninja_lunch.order_repo")
     */
    private $orderRepo;


    /**
     * @DI\Inject("ninja_lunch.acl_manager")
     */
    private $aclManager;

    /**
     * @DI\InjectParams({
     *     "router" = @DI\Inject,
     *     "request" = @DI\Inject
     * })
     */
    public function __construct($request, $router){
        $this->request = $request;
        $router->getContext()->setParameter('order', $request->get('order'));
    }

    /**
     * Lists all FoodOrder\Item entities.
     *
     * @Route("/", name="order_items")
     * @Template()
     */
    public function indexAction($order)
    {
        $entities = $this->repo->findAll();

        return array(
            'entities' => $entities,
            'order'    => $this->getOrder()
        );
    }

    /**
     * Lists all FoodOrder\Item entities.
     *
     * @Template()
     */
    public function listAction($order)
    {
        $page = $this->get('request')->get('page', 1);
        $perPage = 10;

        $entities = $this->repo->getPaginatedList($order, $page, $perPage);

        return array(
            'paginator' => $entities,
        );
    }

    /**
     * Get a simple report for ordering
     *
     * @Template()
     */
    public function reportAction($order){
        $report = $this->repo->getForOrderReport($order);

        return array(
            'report' => $report,
            'order'    => $this->getOrder()
        );
    }

    /**
     * Finds and displays a FoodOrder\Item entity.
     *
     * @Route("/{id}/show", name="order_items_show")
     * @Template()
     */
    public function showAction($id)
    {
        $entity = $this->getItem($id);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'order'      => $this->getOrder(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Creates a new FoodOrder\Item entity.
     *
     * @Route("/create", name="order_items_create")
     * @Method("POST")
     * @Template("NinjaLunchBundle:FoodOrder\Item:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = $this->getOrder()->createItem();
        $form = $this->createForm(new ItemType(), $entity);
        $form->bind($request);

        if ($form->isValid()) {
            $entity->setUser($this->getUser());
            $this->em->persist($entity);
            $this->em->flush();
            $this->aclManager->grant($entity);;
            $this->session->getFlashBag()->add('success', 'Your item was created and added to the order!');

            return $this->redirect($this->generateUrl('order_items_show', array('id' => $entity->getId())));
        }

        $this->session->getFlashBag()->add('warning', 'There were errors with the form!');

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Displays a form to edit an existing FoodOrder\Item entity.
     *
     * @Route("/{item}/edit", name="order_items_edit")
     * @Template()
     * @Security\SecureParam(name="item", permissions="EDIT")
     */
    public function editAction(Item $item)
    {
        $editForm = $this->createForm(new ItemType(), $item);
        $deleteForm = $this->createDeleteForm($item->getId());

        return array(
            'entity'      => $item,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Edits an existing FoodOrder\Item entity.
     *
     * @Route("/{item}/update", name="order_items_update")
     * @Method("POST")
     * @Template("NinjaLunchBundle:FoodOrder\Item:edit.html.twig")
     * @Security\SecureParam(name="item", permissions="EDIT")
     */
    public function updateAction(Request $request, Item $item)
    {
        $deleteForm = $this->createDeleteForm($item->getId());
        $editForm = $this->createForm(new ItemType(), $item);
        $editForm->bind($request);

        if ($editForm->isValid()) {
            $this->em->persist($item);
            $this->em->flush();
            $this->session->getFlashBag()->add('success', 'Your item was updated!');

            return $this->redirect($this->generateUrl('order_items_edit', array('item' => $item->getId())));
        }
        $this->session->getFlashBag()->add('warning', 'There were errors with the form!');

        return array(
            'entity'      => $item,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Finds and displays a form for the Item entity.
     *
     * @Template()
     */
    public function formAction($id = null) {
        if(!$id){
            $entity = $this->getOrder()->createItem();
        } else {
            $entity = $this->getItem($id);
        }

        $form   = $this->createForm(new ItemType(), $entity);

        return array(
            'form'   => $form->createView(),
            'entity' => $entity,
            'order'  => $this->getOrder()
        );
    }

    /**
     * Finds and displays a form for the Item entity.
     *
     * @Template()
     */
    public function deleteFormAction($id) {
        $form   = $this->createDeleteForm($id);
        $entity = $this->getItem($id);

        return array(
            'form'   => $form->createView(),
            'order'  => $this->getOrder(),
            'entity'  => $this->getOrder()
        );
    }

    /**
     * Deletes a FoodOrder\Item entity.
     *
     * @Route("/{item}/delete", name="order_items_delete")
     * @Security\SecureParam(name="item", permissions="EDIT")
     * @Method("POST")
     */
    public function deleteAction(Request $request, Item $item)
    {
        $form = $this->createDeleteForm($item->getId());
        $form->bind($request);

        if ($form->isValid()) {
            $this->em->remove($item);
            $this->em->flush();
            $this->session->getFlashBag()->add('success', 'Your item was deleted!');
        }else{
            $this->session->getFlashBag()->add('warning', 'Your item was not deleted!');
        }

        return $this->redirect($this->generateUrl('order_items'));
    }

    private function getOrder(){
        return $this->orderRepo->find($this->request->get('order'));
    }


    private function getItem($id){
        return $this->repo->find($id);
    }

    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
}

src/Ninja/Lunch/LunchBundle/Controller/FoodOrder/PaymentController.php
<?php

namespace Ninja\Lunch\LunchBundle\Controller\FoodOrder;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Ninja\Lunch\LunchBundle\Entity\FoodOrder;
use Ninja\Lunch\LunchBundle\Entity\FoodOrder\Item;
use Ninja\Lunch\LunchBundle\Form\FoodOrder\ItemType;
use Ninja\Lunch\LunchBundle\Form\FoodOrder\PaymentType;

use JMS\DiExtraBundle\Annotation as DI;
use JMS\SecurityExtraBundle\Annotation as Security;

/**
 * FoodOrder\Item controller.
 *
 * @Route("/orders/{order}/items/{id}/payment")
 */
class PaymentController extends Controller
{

    /**
     * @DI\Inject("doctrine.orm.entity_manager")
     */
    private $em;

    /**
     * @DI\Inject("session")
     */
    private $session;

    /**
     *
     */
    private $request;

    /**
     * @DI\Inject("ninja_lunch.order_item_repo")
     */
    private $repo;

    /**
     * @DI\Inject("ninja_lunch.acl_manager")
     */
    private $aclManager;

    /**
     * @DI\InjectParams({
     *     "router" = @DI\Inject,
     *     "request" = @DI\Inject
     * })
     */
    public function __construct($request, $router){
        $this->request = $request;
        $router->getContext()->setParameter('order', $request->get('order'));
        $router->getContext()->setParameter('item', $request->get('item'));
    }

    /**
     * Lists all FoodOrder\Item entities.
     *
     * @Route(".{_format}", name="order_items_payment_new", defaults={"_format" = "modal"})
     * @Method("GET")
     * @Template()
     */
    public function addAction($order, $id, $_format)
    {
        $entity = $this->getItem($id);
        $form   = $this->createForm(new PaymentType(), $entity);

        return $this->render(sprintf('NinjaLunchBundle:FoodOrder\Payment:add.%s.twig', $_format), array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }

    /**
     * Lists all FoodOrder\Item entities.
     *
     * @Route(".{_format}", name="order_items_payment_update", defaults={"_format" = "modal"})
     * @Method("POST")
     */
    public function updateAction($order, $id, $_format)
    {
        $entity = $this->getItem($id);
        $form = $this->createForm(new PaymentType(), $entity);

        $form->bind($this->request);

        if($form->isValid()){
            $this->em->persist($entity);
            $this->em->flush();
            $this->session->getFlashBag()->add('success', sprintf('Successfully put $%5.2f towards %s', $entity->getAmountPaid(), $entity->getName()));
            return $this->redirect($this->generateUrl('orders_show', array( 'id' => $entity->getOrder()->getId())));
        }

        return $this->render(sprintf('NinjaLunchBundle:FoodOrder\Payment:add.%s.twig', $_format), array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }


    private function getItem($id){
        return $this->repo->find($id);
    }

    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
}

src/Ninja/Lunch/LunchBundle/Controller/FoodOrderController.php
<?php

namespace Ninja\Lunch\LunchBundle\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Ninja\Lunch\LunchBundle\Entity\FoodOrder;

use JMS\DiExtraBundle\Annotation as DI;
use JMS\SecurityExtraBundle\Annotation as Security;

/**
 * FoodOrder controller.
 *
 * @Route("/orders")
 */
class FoodOrderController extends Controller
{
    /**
     * @DI\Inject
     */
    private $session;

    /**
     * @DI\Inject
     */
    private $request;

    /**
     * @DI\Inject("doctrine.orm.entity_manager")
     */
    private $em;

    /**
     * @DI\Inject("ninja_lunch.order_repo")
     */
    private $repo;

    /**
     * Lists all FoodOrder entities.
     *
     * @Route("/", name="orders")
     * @Template()
     */
    public function indexAction()
    {
        $page = $this->request->get('page', 1);
        $entities = $this->em->getRepository('NinjaLunchBundle:FoodOrder')->getPaginatedList($page, 10);

        return array(
            'entities' => $entities,
        );
    }
    /**
     * Lists all FoodOrder entities.
     *
     * @Route("/today.{_format}", defaults={"_format" = "html"}, name="orders_current")
     * @Template()
     */
    public function todaysOrderAction($_format)
    {
        $order = $this->repo->getCurrent();
        return $this->forward('NinjaLunchBundle:FoodOrder:show', array('id' => $order->getId(), '_format' => $_format));
    }

    /**
     * Finds and displays a FoodOrder entity.
     *
     * @Route("/{id}/show.{_format}", defaults={"_format" = "html"}, name="orders_show")
     * @Template()
     */
    public function showAction($id, $_format)
    {
        $entity = $this->getOrder($id);

        return $this->render(sprintf('NinjaLunchBundle:FoodOrder:show.%s.twig', $_format), array(
            'entity' => $entity
        ));
    }

    /**
     * Locks an order
     *
     * @Route("/{id}/lock", name="orders_lock")
     * @Template()
     */
    public function lockAction($id)
    {
        $entity = $this->getOrder($id);

        $entity->setLocked();

        $this->em->persist($entity);
        $this->em->flush();

        $this->session->getFlashBag()->add('success', 'The order was locked!');

        return $this->redirect($this->generateUrl('orders_show', array('id' => $entity->getId())));
    }

    /**
     * Get an order from it's ID
     *
     * @param $id integer The orders id
     * @throws NotFoundException Thrown if the order is not found
     */
    private function getOrder($id){
        $entity = $this->repo->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find that order entity');
        }

        return $entity;
    }
}

src/Ninja/Lunch/LunchBundle/Resources/views/FoodOrder/Item/deleteForm.html.twig
<form action="{{ path('order_items_delete', { 'item': entity.id, order: order.id }) }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <i class="icon-trash"></i> <input type="submit" class="btn delete" value="Delete" />
</form>

src/Ninja/Lunch/LunchBundle/Resources/views/FoodOrder/Item/edit.html.twig
{% extends "NinjaLunchBundle::layout.base.twig" %}
{% block headline %}
Edit item
{% endblock %}
{% block content %}

{% render "NinjaLunchBundle:FoodOrder/Item:form" with { id: entity.id, order: entity.order.id }, { standalone: true } %}
<ul class="record_actions btn-group">
    <a href="{{ path('order_items') }}" class="btn">
        Back to the list
    </a>
    <form action="{{ path('order_items_delete', { 'item': entity.id }) }}" method="post" class="btn">
        {{ form_widget(delete_form) }}
        <button type="submit">Delete</button>
    </form>
</ul>
{% endblock %}

src/Ninja/Lunch/LunchBundle/Resources/views/FoodOrder/Item/form.html.twig
{% if entity.id %}
    {% set formPath = path('order_items_update', { 'item': entity.id }) %}
{% else %}
    {% set formPath = path('order_items_create', { 'item': null }) %}
{% endif %}

<form action="{{ formPath }}" method="post" {{ form_enctype(form) }}>
    <div class="row-fluid">
        <div class="span6">
            {{ form_row(form.item) }}
        </div>
        <div class="span6">
            {{ form_row(form.comments, { attr: { class: 'span12', rows: 3 } }) }}
        </div>
    </div>
    {{ form_rest(form) }}
    <input type="submit" class="btn save" value="Save">
</form>

src/Ninja/Lunch/LunchBundle/Resources/views/FoodOrder/Item/index.html.twig
{% extends "NinjaLunchBundle::layout.base.twig" %}
{% block headline %}
Item list
{% endblock %}
{% block content %}
{% render "NinjaLunchBundle:FoodOrder/Item:list" with { order: order.id }, { standalone: true } %}
<div class="btn-group pull-right">
    <a href="{{ path('orders_show', { id: order.id }) }}" class="btn">
        Back to Order
    </a>
</div>
{% endblock %}

src/Ninja/Lunch/LunchBundle/Resources/views/FoodOrder/Item/list.html.twig
{% set randId = app.request.get('modal_prefix', random()) %}
<table class="records_list table table-hover table-bordered">
    <thead>
        <tr>
            <th>{{ paginator.sortable('Name', 'it.name') | raw }}</th>
            <th>For</th>
            <th>Comments</th>
            <th>Owing</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for entity in paginator %}
    {% set modalId = 'addPayment'~randId~'Modal-' ~ entity.id %}
    <tr>
            <td>
                {% render "NinjaLunchBundle:FoodOrder/Payment:add" with
                    {
                        order: entity.order.id,
                        id: entity.id,
                        _format: 'modal',
                        modalId: modalId
                    },
                    { standalone: true }
                %}
                <a href="{{ path('order_items_show', { 'id': entity.id }) }}">
                    {{ entity.item.name }}
                </a>
            </td>
            <td>
                <a href="{{ path('user_profile', { username: entity.user }) }}">
                    {{ entity.user }}
                </a>
            </td>
            <td>
                {{ entity.comments }}
            </td>
            <td>
                $ {{ entity.amountOwing | number_format(2) }}
            </td>
            <td width="60px">
                <div class="btn-group pull-right">
                  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-cog"></i>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{{ path('order_items_show', { 'id': entity.id }) }}">
                            <i class="icon-list"></i> View
                        </a>
                    </li>
                    <li>
                        <a data-toggle="modal"  href="#{{ modalId }}">

                            <i class="icon-pencil"></i> Update Payment
                        </a>
                    </li>
                    <li>
                        <a href="{{ path('order_items_edit', { 'item': entity.id }) }}">
                            <i class="icon-pencil"></i> Edit
                        </a>
                    </li>
                  </ul>
                </div>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="5">No items have been added to this order</td>
        <tr>
    {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5">
                <div class="navigation pagination-centered">{{ paginator.render | raw }}</div>
            </td>
        </tr>
    </tfoot>
</table>

src/Ninja/Lunch/LunchBundle/Resources/views/FoodOrder/Item/report.html.twig
<table class="records_list table table-hover table-bordered">
    <thead>
        <tr>
            <th>Item</th>
            <th>Count</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
    {% for detail in report %}
    {% set item = detail.item %}
    {% set total = detail.total %}
        <tr>
            <td>
                {{ item.name }}
            </td>
            <td>
                {{ total }}
            </td>
            <td>
                $ {{ item.price * total | number_format(2) }}
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="3">No items have been added to this order</td>
        <tr>
    {% endfor %}
    </tbody>
</table>

src/Ninja/Lunch/LunchBundle/Resources/views/FoodOrder/Item/show.html.twig
{% extends "NinjaLunchBundle::layout.base.twig" %}
{% block headline %}
Viewing item {{ entity.item }}
{% endblock %}
{% block content %}
<table class="record_properties table table-hover">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Comments</th>
            <td>{{ entity.comments }}</td>
        </tr>
        <tr>
            <th>Item</th>
            <td>{{ entity.item }}</td>
        </tr>
        <tr>
            <th>User</th>
            <td>{{ entity.user }}</td>
        </tr>
    </tbody>
</table>

<div class="record_actions btn-group">
    <a href="{{ path('order_items') }}" class="btn">
        Back to the list
    </a>
    <a href="{{ path('orders_show', { 'id': entity.order.id }) }}" class="btn">
        Back to Order
    </a>
    <a href="{{ path('order_items_edit', { 'item': entity.id }) }}" class="btn">
        Edit
    </a>
    <div>
        <form action="{{ path('order_items_delete', { 'item': entity.id }) }}" method="post" class="btn">
            {{ form_widget(delete_form) }}
            <input type="submit" value="delete" />
        </form>
    </div>
</div>

{% endblock %}